/* Generated By:JavaCC: Do not edit this line. ExpressionParserConstants.java */
package br.usp.project_usp.parsers.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int NOT = 7;
  /** RegularExpression Id. */
  int EQUALS = 8;
  /** RegularExpression Id. */
  int GT = 9;
  /** RegularExpression Id. */
  int LT = 10;
  /** RegularExpression Id. */
  int GE = 11;
  /** RegularExpression Id. */
  int LE = 12;
  /** RegularExpression Id. */
  int OK = 13;
  /** RegularExpression Id. */
  int NOT_FOUND = 14;
  /** RegularExpression Id. */
  int POST = 15;
  /** RegularExpression Id. */
  int PUT = 16;
  /** RegularExpression Id. */
  int DELETE = 17;
  /** RegularExpression Id. */
  int COMMA = 18;
  /** RegularExpression Id. */
  int DOT = 19;
  /** RegularExpression Id. */
  int LPAREN = 20;
  /** RegularExpression Id. */
  int RPAREN = 21;
  /** RegularExpression Id. */
  int LBRACKET = 22;
  /** RegularExpression Id. */
  int RBRACKET = 23;
  /** RegularExpression Id. */
  int LBRACE = 24;
  /** RegularExpression Id. */
  int RBRACE = 25;
  /** RegularExpression Id. */
  int SLASH = 26;
  /** RegularExpression Id. */
  int LETTER = 27;
  /** RegularExpression Id. */
  int DIGIT = 28;
  /** RegularExpression Id. */
  int CONSTANT = 29;
  /** RegularExpression Id. */
  int TRUE = 30;
  /** RegularExpression Id. */
  int FALSE = 31;
  /** RegularExpression Id. */
  int IDENTIFIER = 32;
  /** RegularExpression Id. */
  int VARIABLE = 33;
  /** RegularExpression Id. */
  int INVALID_LEXICAL = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"&&\"",
    "\"||\"",
    "\"~\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"ok\"",
    "\"not_found\"",
    "\"post\"",
    "\"put\"",
    "\"delete\"",
    "\",\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"/\"",
    "<LETTER>",
    "<DIGIT>",
    "<CONSTANT>",
    "\"true\"",
    "\"false\"",
    "<IDENTIFIER>",
    "<VARIABLE>",
    "<INVALID_LEXICAL>",
  };

}
